dist: trusty
language: node_js
node_js:
- "stable"
before_script:
- npm install
script:
- npm run build
deploy:
  project: ./build/
  domain: anton-bary.github.io/todolist/
  skip_cleanup: true


language: node_js
node_js:
- 'stable'

cache:
  directories:
    - "node_modules"

script:
  - npm test
  - npm build

deploy:
  provider: pages
  github-token: 2723cdafd427d560bbb140ada4e52633e326caa2  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  repo: anton-bary.github.io/todolist/
  target-branch: main
  on:
    branch: main