language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - "node_modules"

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  github_token: 2f6473f89265bc98b84c908e0411adf5cc563cb8
  committer_from_gh: true
  skip_cleanup: true
  keep_history: true
  local_dir: build
  on:
    branch: main