language: node_js
node_js:
  - "stable"
before_script:
  - npm install
script:
  - npm run build
deploy:
  project: ./build/
  domain: anton-bary.github.io/todolist/
  provider: pages
  skip_cleanup: true
  github_token: e6a9a3344d586a2839b21f66c0b701e359896b63
  keep_history: true
  on:
    branch: main